// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

// Android Firebase Options
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrB381LFFCniWyVXn7-YE0tJ0reWrU5Qo',
    appId: '1:705265906829:android:03ab1fa55566882733d9ae',
    messagingSenderId: '705265906829',
    projectId: 'faceattendance-a9b61',
    storageBucket: 'faceattendance-a9b61.appspot.com',
  );

// iOS Firebase Options
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrB381LFFCniWyVXn7-YE0tJ0reWrU5Qo',
    appId: '1:705265906829:ios:03ab1fa55566882733d9ae',
    messagingSenderId: '705265906829',
    projectId: 'faceattendance-a9b61',
    storageBucket: 'faceattendance-a9b61.appspot.com',
    iosClientId: '8787ygtg5',
    iosBundleId: 'Face.Attendance',
  );



}
